### PR TITLE
Update thumbsup and thumbsdown icons

### PR DESCRIPTION
**Pull request by colebemis**
The current `thumbsup` and `thumbsdown` octicons have always felt a little too cartoony to me and don't match the style of the rest of the icons. I took a stab at redesigning them:

image

### CODE REVIEW

**Comment by samoshin** [comment]
I'm inclined to 👍 it. @tallys?

**Comment by tallys** [comment]
LGTM 👍 👍

**Review by tallys — APPROVED** [review]

**Review by jonrohan — APPROVED** [review]

**Review by camertron — APPROVED** [review]

**Review by keithamus — APPROVED** [review]

**Comment by tallys** [comment]
cc @lukasoppermann

**Review by lukasoppermann — APPROVED** [review]

**Pull request merged**
