### PR TITLE
move packages docs

### PR DESCRIPTION
**Pull request by lukasoppermann**
This is part of the new docs IA: https://github.com/github/primer/issues/1630

### CODE REVIEW

**Comment by colebemis** [comment]
This will break existing links to the package docs. Maybe we should wait to merge this PR until @rezrah has our redirect system set up.

**Comment by rezrah** [comment]
> Maybe we should wait to merge this PR until @rezrah has our redirect system set up.

We can also hardcode redirects in the meantime if someone's able to provide some before/after urls?

**Comment by colebemis** [comment]
@rezrah 

- https://primer.style/octicons/packages/ruby → https://github.com/primer/octicons/tree/main/lib/octicons_gem#readme
- https://primer.style/octicons/packages/jekyll → https://github.com/primer/octicons/tree/main/lib/octicons_jekyll#readme
- https://primer.style/octicons/packages/javascript → https://github.com/primer/octicons/tree/main/lib/octicons_node#readme
- https://primer.style/octicons/packages/react → https://github.com/primer/octicons/tree/main/lib/octicons_react#readme
- https://primer.style/octicons/packages/styled-system →  https://github.com/primer/octicons/tree/main/lib/octicons_styled#readme

**Comment by emilybrick** [comment]
For the other redirects:

- https://primer.style/octicons/ → https://primer.style/design/foundations/icons

- https://primer.style/octicons/guidelines/design → https://primer.style/design/foundations/icons/design-guidelines

- https://primer.style/octicons/accessibility-inset-16 → 
https://primer.style/design/foundations/icons/accessibility-inset-16

**Review by colebemis — APPROVED** [review]

**Pull request merged**
