### PR TITLE
Add discussion state Octicons

### PR DESCRIPTION
**Pull request by gavinmn**
Closes https://github.com/github/primer/issues/1895

image

### CODE REVIEW

**Comment by gavinmn** [comment]
Hearing some feedback that when looking at the icons in context, I think I agree with — the state details are _really small_. I tried more variations to make this work and think this set may be better. 
image

**Comment by antn** [comment]
I think those look great, @gavinmn! Let's go with those.

**Comment by gavinmn** [comment]
> I think those look great, @gavinmn! Let's go with those.

Working on one more "reopen" state to add and then I'll get these out the door.

**Comment by gavinmn** [comment]
Here's a new full proposal for the state icons, increasing the state accessory size by incorporating them into the icon and adding a `discussion-reopen` icon. 
image

**Comment by gavinmn** [comment]
Shipping
image
We're discarding the `reopen` variant in favor of using no icon, or the `discussion-open` icon.

**Pull request merged**
