### PR TITLE
Bump @primer/gatsby-theme-doctocat from 3.1.1 to 4.0.0 in /docs

### PR DESCRIPTION
**Pull request by josepmartins**
Bump `Doctocat` for a consistent reader experience when navigating between different implementation doc sites.

Screenshot 2022-08-01 at 16 28 26

**Reference**
- https://github.com/github/primer/issues/1192

### CODE REVIEW

**Comment by josepmartins** [comment]
@ashygee I used the `Introduction` title for the `Icons` section from [here](https://github.com/github/primer/issues/395), but not really sure about it

**Review by rezrah — APPROVED** [review]

**Review by danielguillan — APPROVED** [review]
Looks good to me!

**Review by danielguillan — APPROVED** [review]

**Comment by ashygee** [comment]
> @ashygee I used the Introduction title for the Icons section as described here: https://github.com/github/primer/issues/395.

@josepmartins I think this is great! I'm not sure about how I feel about the collection falling under "Introduction" but for now, I feel this works. I think once we get further into how we want to get deeper with our icon infrastructure we can reorganize to account for the new work that comes out of that. Thank you for doing this!

**Review by ashygee — APPROVED** [review]
Thank you! 🚀

**Pull request merged**
