### PR TITLE
Add new sparkles icon

### PR DESCRIPTION
**Pull request by lukasoppermann**
This icon was request by @dthoma1.

Fixes https://github.com/github/primer/issues/4430

### CODE REVIEW

**Review by colebemis — COMMENTED** [review]
Should we call this `sparkles-fill`? That leaves the option to have an outline version in the future and is consistent with the existing `sparkle-fill` icon: https://primer.style/foundations/icons/sparkle-fill-16

**Comment by dthoma1** [comment]
This icon fits our needs for the docs ai assistant project. ✨

**Comment by lukasoppermann** [comment]
@colebemis is there a naming convention for icons somewhere?

**Comment by tallys** [comment]
@colebemis you are a gem and an eternal champion of Octicons, thank you for reviewing!
@lukasoppermann thanks so much for pushing this through to support @dthoma1 !!!

**Review by tallys — APPROVED** [review]

**Pull request merged**
