### PR TITLE
Add icon-specific className to React default props

### PR DESCRIPTION
**Pull request by FloEdelmann**
In GitHub, all the icons have a class `octicon-${key}`, e.g. `octicon-arrow-both` for the `ArrowBothIcon`. This PR adds this class to the React components' default props:

```diff
  function ArrowBothIcon(props) {
    // …
    return <svg {...getSvgProps({...props, svgDataByHeight})} />
  }

  ArrowBothIcon.defaultProps = {
-   className: 'octicon',
+   className: 'octicon octicon-arrow-both',
    size: 16,
    verticalAlign: 'text-bottom'
  }
```

### CODE REVIEW

**Comment by fregante** [comment]
I think this makes sense since by default it also has the `octicon` class as well

**Comment by fregante** [comment]
Ping on this, it would be pretty useful and it's a simple addition

**Comment by FloEdelmann** [comment]
@colebemis @ashygee Could you please have a quick look at this PR?

**Comment by ashygee** [comment]
@FloEdelmann Thanks for this and sorry for the delay! I've assigned this to @colebemis and we'll review this week. Apologies for not seeing this sooner.

**Comment by FloEdelmann** [comment]
@colebemis Sorry to bother you again, but given this is literally only one changed line, I don't understand why you still didn't review. Having that extra class name would be really helpful, e.g. in https://github.com/sindresorhus/refined-github/pull/3227.

**Comment by fregante** [comment]
No rush Flo 🤗

**Comment by yakov116** [comment]
@colebemis friendly bump

**Comment by yakov116** [comment]
@colebemis @ashygee its almost 7 months since this PR has been opened and 3 releases. Any chance this can be reviewed?

**Review by colebemis — APPROVED** [review]
Looks great! Sorry for the delay.

We'll ship this in our next release.

**Pull request merged**
