### PR TITLE
adding printer icon

### PR DESCRIPTION
**Pull request by pinguxx**

### CODE REVIEW

**Comment by pinguxx** [comment]
I didn't touch any code, not sure why this is not compiling, what configuration do i need to add in travis to make it compile?

**Comment by jonrohan** [comment]
@pinguxx no worries, this pr is mostly meant to initiate the collaboration process. It's not meant to be merged. If we decide to add it to the main set, we'll pull it into the design file. Thanks for the contribution 🥇

**Comment by pinguxx** [comment]
any feedback on this?

**Comment by jonrohan** [comment]
@pinguxx sorry about the delay in responding. I spoke with the team, and we are not in a place right now to accept icons that aren't used by the github.com website and suite of apps. We hope to improve our design guidelines in the future to allow for contributions from the community.

**Pull request closed without merging**
