### PR TITLE
Add sidebar expand and collapse icons

### PR DESCRIPTION
**Pull request by colebemis**
image

### CODE REVIEW

**Comment by ashygee** [comment]
@colebemis is `collapse` and `expand` the correct descriptor for this? not `open`/`close`?

**Comment by colebemis** [comment]
@ashygee I'm fine with either.

**Comment by colebemis** [comment]
`expand`/`collapse` feel like they represent the action of "expanding" or "collapsing" which is how the icons will be used. `open`/`close` feel more like they could be states of the sidebar.

**Comment by ashygee** [comment]
> `expand`/`collapse` feel like they represent the action of "expanding" or "collapsing" which is how the icons will be used. `open`/`close` feel more like they could be states of the sidebar.

This makes perfect sense. let's keep as is then! 🚀 it!

**Pull request merged**
