### PR TITLE
fix(octicons_react): remove build from npm package files

### PR DESCRIPTION
**Pull request by joshblack**
Closes https://github.com/primer/octicons/pull/1002

This removes `build` from the list of `files` for the npm package. These files are not accessible since we currently use the `exports` field so removing this should be compatible within semver (but let me know if not!)

### CODE REVIEW

**Review by broccolinisoup — APPROVED** [review]
>These files are not accessible since we currently use the exports field so removing this should be compatible within semver (but let me know if not!)

That makes sense to me!

**Comment by fregante** [comment]
Hmm why not just merge my PRs?

**Comment by camertron** [comment]
@fregante I'm not 100% sure in this case, but we usually do this because certain actions won't run from forks.

**Comment by joshblack** [comment]
Hi @fregante, I'm so sorry about that, I wasn't aware of it. Totally my fault!

**Comment by fregante** [comment]
No problem to leave as is, I was just wondering

**Pull request merged**
