### PR TITLE
added new workflow icons

### PR DESCRIPTION
**Pull request by ashygee**
Adding two new icons for Actions

Name | Icon
--- | ---
workflow | workflow
workflow-all | workflow-all

### CODE REVIEW

**Comment by jonrohan** [comment]
This didn't work, can you update the filename in https://github.com/primer/octicons/blob/add-workflow-icons/.github/workflows/push.yml#L17

Also delete the `.github/main.workflow` file

**Comment by jonrohan** [comment]
```
Octicons have keywords The octicon "workflow" doesn't have any keywords
```
❌

**Comment by jonrohan** [comment]
Release is releasing, thank you.

**Comment by jasonlong** [comment]
Yay, thanks @jonrohan and @ashygee :heart:

**Pull request closed without merging**
